### ISSUE TITLE
Fix: Typescript Example

### ISSUE THREAD

**Issue by jyotman** [mokuteki225/propagated-transactions#9]
Hi @mokuteki225 

Thanks for this brilliant package. I was looking for something like this specifically.

I faced an issue recently when using it with Typescript - 

The `PropagatedTransaction` class expects a _type variable_ to be passed whenever using it in the code. The current Typescript example in the documentation suggests doing the following - 

```typescript
// Creation
export const ptx = new PropagatedTransaction(TypeormTransactionRunner);

// Usage
export class UserService {
  constructor(
    private readonly ptx: PropagatedTransaction, 
    private readonly userRepository: IUserRepository, 
    private readonly walletRepository: IWalletRepository, 
  ) {}
```

But according to this class definition - 

```typescript
export class PropagatedTransaction<T extends unknown> {
  connection: T;

  constructor(runner: ITransactionRunner<T>, als?: AsyncLocalStorage<T>);

  run<R>(callback: () => R, isolationLevel?: IsolationLevelValue): R;
}
```
 
Typescript would force to pass the _type variable_ to the `PropagatedTransaction` class and it will look like this - 
 
```typescript
// Creation
export const ptx = new PropagatedTransaction<QueryRunner>(TypeormTransactionRunner);

// Usage
export class UserService {
  constructor(
    private readonly ptx: PropagatedTransaction<QueryRunner>, 
    private readonly userRepository: IUserRepository, 
    private readonly walletRepository: IWalletRepository, 
  ) {}
```

Should I fix this example?

Also, I like how the library promotes abstraction, I created an `interface` for `PropagatedTransaction` myself so that my `UserService` class doesn't have to rely upon the concrete _type variable_ `QueryRunner`, which would expose the implementation details of the underlying database being used to the service. Here's the interface - 

```typescript
import { IsolationLevelValue } from '@mokuteki/propagated-transactions';

// Interface for import { PropagatedTransaction } from '@mokuteki/propagated-transactions';
export default interface IPropagatedTransaction {
  connection: unknown;
  run<R>(callback: () => R, isolationLevel?: IsolationLevelValue): R;
}
```

Then I wrote my UserService like the following - 

```typescript
// Usage
export class UserService {
  constructor(
    private readonly ptx: IPropagatedTransaction, 
    private readonly userRepository: IUserRepository, 
    private readonly walletRepository: IWalletRepository, 
  ) {}
```

Let me what you think of this. Also, I'm happy to create a PR for the following changes if you approve 😄

**Comment by vkondratiuk482** [comment]
Hi @jyotman

Thanks for your feedback, I am really glad this package came in handy for you.

However, the way it is supposed to be done in business layer is via providing `unknown` as a generic type, e. g. `PropagatedTransaction<unknown>`. Since `PropagatedTransaction` already uses underlying abstraction under the hood (`ITransactionRunner`), I am not sure if it makes any sense to also hide `PropagatedTransaction` behind an interface

Anyway, I've just landed [a PR](https://github.com/mokuteki225/propagated-transactions/pull/10) that fixed the documentation, thank you for your contribution! Feel free to reopen the issue in case there is something else

**Comment by jyotman** [comment]
@mokuteki225 oh I see, yes the `unknown` type can work well 👍 Thanks for the suggestion and fixing the docs 🙌
